[package]
name = "voronoi_fps"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[[bench]]
name = "bench"
harness = false

[dependencies]
ndarray = {version = "0.14", features = ["rayon"]}
soa_derive = "0.10"
rayon = "1"
thread_local = "1"
once_cell = "1"
parking_lot = "*"

tracing = "0.1"
tracing-subscriber = "0.2"
tracing-span-time = {path = "../../../code/tracing-span-time"}

[dev-dependencies]
ndarray-npy = "0.7"
criterion = {version = "0.3", features = ["html_reports"]}
